version: "3"

networks:
  localnetwork:
    driver: bridge

services:
  mysqldb:
    container_name: mysqldb-compose
    image: mysql/mysql-server
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASS
    ports:
      - "3306:3306"
    networks:
      - localnetwork
    volumes:
      - /home/user123/.docker/mysql:/var/lib/mysql

  backend:
    container_name: backend
    build: ./consumer-back-end
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - ./.m2:/root/.m2
    stdin_open: true
    tty: true
    depends_on:
      - mysqldb
    networks:
      - localnetwork

  frontend:
    container_name: frontend
    build: ./consumer-front-end
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    volumes:
      - ./.m2:/root/.m2
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - localnetwork
